# Generated by Django 5.2.6 on 2025-10-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('online', 'Online Payment')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
