# Generated by Django 5.2.6 on 2025-11-16 09:23

from django.db import migrations


def migrate_rent_payments_to_unified_payment(apps, schema_editor):
    """
    Migrate RentPayment records to unified Payment model
    """
    RentPayment = apps.get_model('rent', 'RentPayment')
    Payment = apps.get_model('payments', 'Payment')
    
    rent_payments = RentPayment.objects.all()
    migrated_count = 0
    
    for rent_payment in rent_payments:
        # Map status: 'completed' -> 'completed', 'pending' -> 'pending', 'failed' -> 'failed', 'cancelled' -> 'cancelled'
        status_mapping = {
            'completed': 'completed',
            'pending': 'pending',
            'failed': 'failed',
            'cancelled': 'cancelled',
        }
        payment_status = status_mapping.get(rent_payment.status, 'pending')
        
        # Create unified Payment record
        Payment.objects.create(
            rent_invoice=rent_payment.invoice,
            lease=rent_payment.lease,
            tenant=rent_payment.tenant,
            amount=rent_payment.amount,
            payment_method=rent_payment.payment_method,
            paid_date=rent_payment.payment_date,
            status=payment_status,
            transaction_ref=rent_payment.transaction_id or rent_payment.reference_number,
            reference_number=rent_payment.reference_number,
            transaction_id=rent_payment.transaction_id,
            processor_response=rent_payment.processor_response,
            notes=rent_payment.notes,
            recorded_by=rent_payment.recorded_by,
            created_at=rent_payment.created_at,
            updated_at=rent_payment.updated_at,
        )
        migrated_count += 1
    
    print(f"Migrated {migrated_count} RentPayment records to unified Payment model")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - not implemented as we're deprecating RentPayment
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_unify_payment_system'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_rent_payments_to_unified_payment, reverse_migration),
    ]
