# Generated by Django 5.2.6 on 2025-11-16 09:23

from django.conf import settings
from django.db import migrations


def migrate_property_payments_to_unified_payment(apps, schema_editor):
    """
    Migrate properties.Payment records to unified Payment model
    """
    PropertyPayment = apps.get_model('properties', 'Payment')
    Payment = apps.get_model('payments', 'Payment')
    # Get User model using AUTH_USER_MODEL setting
    user_app, user_model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app, user_model)
    
    property_payments = PropertyPayment.objects.all()
    migrated_count = 0
    skipped_count = 0
    
    # Map payment methods
    payment_method_mapping = {
        'card': 'credit_card',
        'cash': 'cash',
        'bank_transfer': 'bank_transfer',
        'mobile_money': 'mobile_money',
        'check': 'check',
        'other': 'online',  # Map 'other' to 'online'
    }
    
    # Map status
    status_mapping = {
        'active': 'successful',
        'refunded': 'cancelled',
        'cancelled': 'cancelled',
    }
    
    for prop_payment in property_payments:
        # Map payment method
        payment_method = payment_method_mapping.get(prop_payment.payment_method, 'cash')
        
        # Map status
        payment_status = status_mapping.get(prop_payment.status, 'pending')
        
        # Get tenant from booking
        # Booking has 'customer' field, not 'tenant'
        # Try to find User by customer email, or use booking.created_by as fallback
        booking = prop_payment.booking
        tenant = None
        
        # Try to get user from customer's email
        if booking.customer and booking.customer.email:
            try:
                tenant = User.objects.get(email=booking.customer.email)
            except User.DoesNotExist:
                pass
        
        # Fallback to booking.created_by if no user found by email
        if not tenant and booking.created_by:
            tenant = booking.created_by
        
        # Skip if we still can't find a tenant
        if not tenant:
            skipped_count += 1
            print(f"Skipping payment {prop_payment.id}: No tenant/user found for booking {booking.id}")
            continue
        
        # Convert DateTime to Date
        paid_date = prop_payment.payment_date.date() if prop_payment.payment_date else None
        
        # Create unified Payment record
        Payment.objects.create(
            booking=prop_payment.booking,
            tenant=tenant,
            amount=prop_payment.amount,
            payment_method=payment_method,
            paid_date=paid_date,
            status=payment_status,
            transaction_ref=prop_payment.transaction_reference,
            reference_number=prop_payment.transaction_reference,
            notes=prop_payment.notes,
            recorded_by=prop_payment.recorded_by,
            created_at=prop_payment.created_at,
            updated_at=prop_payment.updated_at,
        )
        migrated_count += 1
    
    print(f"Migrated {migrated_count} Property Payment records to unified Payment model")
    if skipped_count > 0:
        print(f"Skipped {skipped_count} Property Payment records (no tenant/user found)")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - not implemented as we're deprecating properties.Payment
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_migrate_rent_payments'),
        ('properties', '0005_houserentreminder_houserentreminderlog_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_property_payments_to_unified_payment, reverse_migration),
    ]
