# Generated by Django 5.2.6 on 2025-11-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_migrate_property_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='azam_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
