# Generated by Django 5.2.6 on 2025-11-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_payment_provider_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
