# Generated by Django 5.2.6 on 2026-01-04 16:01

from django.db import migrations


def update_payment_status_forward(apps, schema_editor):
    """Update 'successful' status to 'completed' in Payment model"""
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(status='successful').update(status='completed')


def update_payment_status_reverse(apps, schema_editor):
    """Reverse: Update 'completed' status back to 'successful'"""
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(status='completed').update(status='successful')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymentprovider_created_at'),
    ]

    operations = [
        migrations.RunPython(
            update_payment_status_forward,
            update_payment_status_reverse,
        ),
    ]
