# Generated by Django 5.2.6 on 2026-01-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Receipt/proof of payment (for cash payments only)', null=True, upload_to='payment_receipts/%Y/%m/'),
        ),
    ]
