# Generated by Django 5.2.6 on 2026-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_add_receipt_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('AIRTEL', 'AIRTEL'), ('TIGO', 'TIGO'), ('MPESA', 'MPESA (Vodacom)'), ('HALOPESA', 'HALOPESA')], help_text='Mobile money provider (required for mobile_money payments)', max_length=20, null=True),
        ),
    ]
