# Generated by Django 5.2.6 on 2026-01-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money (AZAM Pay)'), ('online', 'Online Payment (AZAM Pay)')], max_length=20),
        ),
    ]
