"""
Django settings for Maisha_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import Csv, Config, RepositoryEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Explicitly set .env file location to ensure it's found regardless of working directory
# This fixes the issue where python-decouple can't find .env when web server runs from different directory
ENV_FILE = BASE_DIR / '.env'

# Create a config function that explicitly uses the .env file from project root
if ENV_FILE.exists():
    # Use Config with RepositoryEnv to explicitly load from project root
    # This ensures .env is found even if web server runs from different directory
    _env_repo = RepositoryEnv(str(ENV_FILE))
    _config_obj = Config(_env_repo)
    config = _config_obj
else:
    # Fallback to default behavior if .env doesn't exist
    from decouple import config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure--lcr^7cu6oeuae)6&4(*s8h_4e@2aph+104tmjtm%2nt0n0*m6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='True', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())

# Increase field limit for forms with many fields (e.g., property formsets)
# Default is 1000, increased significantly for property forms with images and amenities
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # For template filters like intcomma, filesizeformat
    'accounts',
    'properties',  # Properties management app
    'payments',
    'documents',  # Leases, bookings, and documents module
    'rent',  # Rent management and payment tracking
    'maintenance',  # Maintenance requests and management
    'reports',  # Reporting and analytics module
    'complaints',  # Complaints and feedback management
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Token blacklist for strict token revocation
    'corsheaders',
    'drf_yasg',  # Swagger API documentation
    'django_filters',  # For API filtering
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom middleware for session timeout enforcement (must be after AuthenticationMiddleware)
    'accounts.middleware.permissions.SessionTimeoutMiddleware',
    # Custom middleware for role-based permissions
    'accounts.middleware.permissions.RolePermissionMiddleware',
    # Custom middleware for activity logging
    'accounts.middleware.permissions.ActivityLoggingMiddleware',
]

ROOT_URLCONF = 'Maisha_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.navigation_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'Maisha_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME', default='maisha'),
        'USER': config('DATABASE_USER', default='postgres'),
        'PASSWORD': config('DATABASE_PASSWORD', default='alfred'),
        'HOST': config('DATABASE_HOST', default='localhost'),
        'PORT': config('DATABASE_PORT', default='5432'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}

# Database configuration: PostgreSQL "maisha" database only
# NO SQLite fallback - must use PostgreSQL
# Database credentials can be set via environment variables:
# DATABASE_NAME, DATABASE_USER, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Use an absolute path for STATIC_URL so the static template tag produces
# absolute URLs (e.g. /static/...). A missing leading slash can produce
# relative URLs and cause 404s in templates.
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'assets',
    BASE_DIR / 'vendors',
]
LOGIN_URL = '/login/'

# Media files (user uploaded)
MEDIA_URL = '/media/'
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Firebase integration removed (unused)

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.GracefulJWTAuthentication',  # Custom JWT auth that gracefully handles invalid tokens
        'rest_framework.authentication.SessionAuthentication',  # Needed for web-based API calls
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Rate limiting/throttling configuration
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Anonymous users: 100 requests per hour
        'user': '1000/hour',  # Authenticated users: 1000 requests per hour
        'auth': '10/minute',  # Authentication endpoints: 10 requests per minute
        'search': '30/minute',  # Search endpoints: 30 requests per minute
    }
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Swagger Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'DEFAULT_MODEL_RENDERING': 'model',
}

# CORS Configuration for Flutter app - Environment-based
# Get environment (defaults to development for backward compatibility)
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')

if ENVIRONMENT == 'production':
    # Production: Only allow specific origins
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        # Add your production mobile app origins here
        # Example: "https://your-mobile-app-domain.com",
        # Example: "https://api.your-domain.com",
    ]
    # If no origins specified, allow common production patterns
    if not CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS = [
            "https://api.maisha.local",
            "https://app.maisha.local",
        ]
else:
    # Development: Allow all origins for testing
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# =============================================================================
# SESSION CONFIGURATION
# =============================================================================
# Session timeout settings for automatic logout on inactivity
# Standard timeout: 30 minutes of inactivity (1800 seconds)
# This is a common standard for business/property management systems
# Industry standards:
# - Banking/Financial: 15-20 minutes
# - Business/Property Management: 30 minutes (recommended)
# - Healthcare: 15-30 minutes
# - General Web Apps: 1-2 hours
SESSION_COOKIE_AGE = 60 * 30  # 30 minutes in seconds (1800 seconds)

# Save session on every request - this implements "sliding expiration"
# When True: Session timeout resets on every request (user stays logged in while active)
# When False: Session expires after SESSION_COOKIE_AGE regardless of activity
# Recommended: True (allows active users to stay logged in, logs out only on inactivity)
SESSION_SAVE_EVERY_REQUEST = True

# Session expires when browser closes (False = session persists across browser restarts)
# When False: User stays logged in even after closing browser, but session expires after inactivity
# When True: Session expires immediately when browser closes
# Recommended: False (better UX, still secure with inactivity timeout)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Security settings for session cookies
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie (XSS protection)
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# Session engine - using database backend (default)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Set SESSION_COOKIE_SECURE based on environment (must be after ENVIRONMENT is defined)
# In production, set SESSION_COOKIE_SECURE = True to only send cookies over HTTPS
if ENVIRONMENT == 'production':
    SESSION_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SECURE = False

# =============================================================================
# Logging configuration - Enhanced for API monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'api.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'api_errors.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'accounts.api_views': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'properties.api_views': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'payments.api_views': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'documents.api_views': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'rent.api_views': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'maintenance.api_views': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'reports.api_views': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'complaints.api_views': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# =============================================================================
# AZAM PAY CONFIGURATION
# =============================================================================
# AZAM Pay Payment Gateway Settings
# Documentation: https://developerdocs.azampay.co.tz/redoc
# 
# To get credentials:
# 1. Register at https://sandbox.azampay.co.tz/ (for testing)
# 2. Complete KYC documentation
# 3. Register your application to get Client ID, Client Secret, and API Key
# 4. Configure webhook URL in AZAM Pay dashboard

AZAM_PAY_CLIENT_ID = config('AZAM_PAY_CLIENT_ID', default='')
AZAM_PAY_CLIENT_SECRET = config('AZAM_PAY_CLIENT_SECRET', default='')
AZAM_PAY_API_KEY = config('AZAM_PAY_API_KEY', default='')
AZAM_PAY_APP_NAME = config('AZAM_PAY_APP_NAME', default='Maisha Property Management')
AZAM_PAY_SANDBOX = config('AZAM_PAY_SANDBOX', default='True', cast=bool)
AZAM_PAY_BASE_URL = config('AZAM_PAY_BASE_URL', default='https://sandbox.azampay.co.tz')
AZAM_PAY_PRODUCTION_URL = config('AZAM_PAY_PRODUCTION_URL', default='https://api.azampay.co.tz')
AZAM_PAY_WEBHOOK_SECRET = config('AZAM_PAY_WEBHOOK_SECRET', default='')
AZAM_PAY_VENDOR_ID = config('AZAM_PAY_VENDOR_ID', default='')
AZAM_PAY_MERCHANT_ACCOUNT = config('AZAM_PAY_MERCHANT_ACCOUNT', default='')
# Pre-generated token from AZAMpay dashboard (for sandbox testing)
# Get this from: Dashboard → Register App → Token field
AZAM_PAY_TOKEN = config('AZAM_PAY_TOKEN', default='')

# Test phone number for sandbox testing (optional)
# Use this if customer doesn't have a phone number or for testing
AZAM_PAY_TEST_PHONE = config('AZAM_PAY_TEST_PHONE', default='255758285812')

# Base URL for webhook callbacks
BASE_URL = config('BASE_URL', default='http://localhost:8000')

# AZAMpay Webhook URL (optional - overrides BASE_URL for webhooks)
# For local testing with ngrok: https://abc123.ngrok.io/api/v1/payments/webhook/azam-pay/
# For production: https://portal.maishaapp.co.tz/api/v1/payments/webhook/azam-pay/
AZAM_PAY_WEBHOOK_URL = config('AZAM_PAY_WEBHOOK_URL', default='https://portal.maishaapp.co.tz/api/v1/payments/webhook/azam-pay/')

# =============================================================================
# SERPAPI CONFIGURATION
# =============================================================================
# SerpApi for Google Maps geocoding and search
# Documentation: https://serpapi.com/
# 
# To get API key:
# 1. Sign up at https://serpapi.com/
# 2. Get your API key from dashboard
# 3. Add to .env file: SERPAPI_KEY=your_api_key_here
# 
# Plans:
# - Free: 250 searches/month
# - Starter: $25/month - 1,000 searches
# - Developer: $75/month - 5,000 searches
# - Production: $150/month - 15,000 searches

SERPAPI_KEY = config('SERPAPI_KEY', default='')
