# Generated by Django 5.2.5 on 2025-09-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customrole'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrole',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='customrole',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customrole',
            name='django_group',
        ),
        migrations.RemoveField(
            model_name='customrole',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
