# Generated by Django 5.2.6 on 2025-10-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_navigationitem_rolenavigationpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolenavigationpermission',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='icon',
            field=models.TextField(help_text='HTML icon code (SVG or FontAwesome)'),
        ),
    ]
