# Generated by Django 5.2.6 on 2025-10-08 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_rolenavigationpermission_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('payment', 'Payment'), ('booking', 'Booking'), ('complaint', 'Complaint'), ('maintenance', 'Maintenance'), ('lease', 'Lease'), ('document', 'Document')], max_length=20)),
                ('description', models.TextField()),
                ('content_type', models.CharField(help_text='Type of object (Property, Payment, etc.)', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount in TZS', max_digits=15, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data as JSON')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_ac_timesta_ffc3ad_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_ac_user_id_9bf4ca_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_ac_action_448a74_idx')],
            },
        ),
    ]
