# Generated by Django 4.2.7 on 2025-11-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='deactivation_reason',
            field=models.TextField(blank=True, help_text='Reason for deactivation (shown to user on login attempt)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deactivated',
            field=models.BooleanField(default=False, help_text='If True, user cannot login and will see deactivation message'),
        ),
    ]
