# Generated by Django 5.2.6 on 2025-11-15 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_deactivated_at_profile_deactivated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('password_reset', 'Password Reset Request'), ('user_approval', 'User Approval'), ('payment', 'Payment'), ('complaint', 'Complaint'), ('maintenance', 'Maintenance'), ('system', 'System')], default='system', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data as JSON')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(blank=True, help_text='Related user (e.g., user requesting password reset)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who requested (for password reset)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_no_created_4d1468_idx'), models.Index(fields=['is_read', '-created_at'], name='accounts_no_is_read_78f484_idx'), models.Index(fields=['notification_type', '-created_at'], name='accounts_no_notific_681bde_idx')],
            },
        ),
    ]
