# Generated by Django 5.2.6 on 2025-10-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum capacity (for venues)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the property is active/visible'),
        ),
        migrations.AddField(
            model_name='property',
            name='room_types',
            field=models.JSONField(blank=True, help_text='Room types and counts (for hotels/lodges)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of rooms (for hotels/lodges)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='venue_type',
            field=models.CharField(blank=True, help_text='Type of venue (conference, wedding, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, help_text='Number of bathrooms', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, help_text='Number of bedrooms (not applicable for venues)', null=True),
        ),
    ]
