# Generated by Django 5.2.6 on 2025-10-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_customer_booking_complaint_payment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
