# Generated by Django 5.2.6 on 2025-10-25 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('phone', 'Phone Call')], max_length=20)),
                ('reminder_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('days_before_due', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message_content', models.TextField()),
                ('custom_message', models.TextField(blank=True)),
                ('reminder_sequence', models.IntegerField(default=1, help_text='Sequence number of this reminder (1st, 2nd, etc.)')),
                ('is_overdue', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(blank=True, max_length=50)),
                ('delivery_error', models.TextField(blank=True)),
                ('delivery_reference', models.CharField(blank=True, max_length=100)),
                ('tenant_response', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(limit_choices_to={'property_obj__property_type__name__iexact': 'house'}, on_delete=django.db.models.deletion.CASCADE, related_name='house_reminders', to='properties.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_house_reminders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_reminders', to='properties.customer')),
                ('property_obj', models.ForeignKey(limit_choices_to={'property_type__name__iexact': 'house'}, on_delete=django.db.models.deletion.CASCADE, related_name='house_reminders', to='properties.property')),
            ],
            options={
                'verbose_name': 'House Rent Reminder',
                'verbose_name_plural': 'House Rent Reminders',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='HouseRentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Reminder Created'), ('scheduled', 'Reminder Scheduled'), ('sent', 'Reminder Sent'), ('failed', 'Reminder Failed'), ('cancelled', 'Reminder Cancelled'), ('escalated', 'Escalated'), ('payment_received', 'Payment Received'), ('tenant_response', 'Tenant Response')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='properties.houserentreminder')),
            ],
            options={
                'verbose_name': 'Rent Reminder Log',
                'verbose_name_plural': 'Rent Reminder Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseRentReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100)),
                ('schedule_type', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('custom', 'Custom')], max_length=20)),
                ('days_before_due', models.IntegerField(default=7)),
                ('overdue_interval_days', models.IntegerField(default=3)),
                ('max_reminders', models.IntegerField(default=5)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('send_time', models.TimeField(default='09:00:00')),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=50)),
                ('custom_days', models.JSONField(blank=True, default=list, help_text='Custom days for custom schedule type')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_obj', models.ForeignKey(limit_choices_to={'property_type__name__iexact': 'house'}, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='properties.property')),
            ],
            options={
                'verbose_name': 'Rent Reminder Schedule',
                'verbose_name_plural': 'Rent Reminder Schedules',
                'ordering': ['property_obj', 'schedule_name'],
            },
        ),
        migrations.CreateModel(
            name='HouseRentReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_due', models.IntegerField(default=7, help_text='Days before due date to send first reminder')),
                ('overdue_reminder_interval', models.IntegerField(default=3, help_text='Days between overdue reminders')),
                ('max_overdue_reminders', models.IntegerField(default=5, help_text='Maximum number of overdue reminders to send')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('custom_email_template', models.TextField(blank=True, help_text='Custom email template (optional)')),
                ('custom_sms_template', models.TextField(blank=True, help_text='Custom SMS template (optional)')),
                ('grace_period_days', models.IntegerField(default=5, help_text='Grace period before late fees apply')),
                ('auto_escalate_enabled', models.BooleanField(default=True, help_text='Automatically escalate to property manager after max reminders')),
                ('escalation_email', models.EmailField(blank=True, help_text='Email to notify for escalation', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_obj', models.ForeignKey(limit_choices_to={'property_type__name__iexact': 'house'}, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='properties.property')),
            ],
            options={
                'verbose_name': 'House Rent Reminder Settings',
                'verbose_name_plural': 'House Rent Reminder Settings',
            },
        ),
        migrations.CreateModel(
            name='HouseRentReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('email', 'Email Template'), ('sms', 'SMS Template'), ('push', 'Push Notification Template')], max_length=20)),
                ('category', models.CharField(choices=[('upcoming', 'Upcoming Payment'), ('overdue_1', 'First Overdue'), ('overdue_2', 'Second Overdue'), ('overdue_3', 'Third Overdue'), ('final_notice', 'Final Notice'), ('escalation', 'Escalation Notice')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('variables_help', models.TextField(blank=True, help_text='Available variables: {{tenant_name}}, {{property_title}}, {{due_date}}, {{amount}}, {{days_overdue}}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rent Reminder Template',
                'verbose_name_plural': 'Rent Reminder Templates',
                'ordering': ['template_type', 'category'],
                'unique_together': {('template_type', 'category', 'is_default')},
            },
        ),
        migrations.AddIndex(
            model_name='houserentreminder',
            index=models.Index(fields=['booking', 'reminder_sequence'], name='properties__booking_9956cb_idx'),
        ),
        migrations.AddIndex(
            model_name='houserentreminder',
            index=models.Index(fields=['scheduled_date', 'reminder_status'], name='properties__schedul_0cb01f_idx'),
        ),
        migrations.AddIndex(
            model_name='houserentreminder',
            index=models.Index(fields=['due_date', 'is_overdue'], name='properties__due_dat_d8442a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='houserentremindersettings',
            unique_together={('property_obj',)},
        ),
    ]
