# Generated by Django 5.2.6 on 2025-11-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_houserentreminder_houserentreminderlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='booking_expiration_hours',
            field=models.PositiveIntegerField(default=12, help_text='Hours after booking creation to cancel if no payment (partial or full) is made. Set to 0 to disable auto-cancellation.'),
        ),
    ]
