# Generated by Django 5.2.6 on 2025-11-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_add_booking_expiration_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='properties.region')),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['region', 'name'],
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, help_text='District within the selected region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.district'),
        ),
    ]
