# Generated by Django 5.2.6 on 2025-11-19 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_district_model_and_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='admin_comments',
            field=models.TextField(blank=True, help_text='Admin comments/notes about the property', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the property was approved', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the property has been approved by admin'),
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if property was rejected', null=True),
        ),
    ]
