# Generated by Django 5.2.6 on 2025-11-26 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_azam_pay_fields'),
        ('properties', '0008_add_property_approval_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost for visit-only access (house properties only). User pays this to get owner contact and location.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PropertyVisitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_visit_payments', to='payments.payment')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_payments', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_visit_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Visit Payment',
                'verbose_name_plural': 'Property Visit Payments',
                'db_table': 'property_visit_payments',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'user')},
            },
        ),
    ]
