# Generated by Django 5.2.6 on 2025-12-12 10:33

from django.db import migrations, models


def set_rent_period_defaults(apps, schema_editor):
    """Set rent_period defaults based on property type"""
    Property = apps.get_model('properties', 'Property')
    
    # Set 'day' for hotels, lodges, and venues
    day_property_types = ['hotel', 'lodge', 'venue']
    for prop_type_name in day_property_types:
        Property.objects.filter(
            property_type__name__iexact=prop_type_name
        ).update(rent_period='day')
    
    # All other properties default to 'month' (already set by field default)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_visit_cost_propertyvisitpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_period',
            field=models.CharField(choices=[('month', 'Per Month'), ('day', 'Per Day'), ('week', 'Per Week'), ('year', 'Per Year')], default='month', help_text='Duration for which the rent amount applies (e.g., per month for houses, per day for hotels/lodges)', max_length=10),
        ),
        migrations.RunPython(set_rent_period_defaults, migrations.RunPython.noop),
    ]
