# Generated by Django 5.2.6 on 2026-01-04 16:02

from django.db import migrations


def update_visit_payment_status_forward(apps, schema_editor):
    """Update 'successful' status to 'completed' in PropertyVisitPayment model"""
    PropertyVisitPayment = apps.get_model('properties', 'PropertyVisitPayment')
    PropertyVisitPayment.objects.filter(status='successful').update(status='completed')


def update_visit_payment_status_reverse(apps, schema_editor):
    """Reverse: Update 'completed' status back to 'successful'"""
    PropertyVisitPayment = apps.get_model('properties', 'PropertyVisitPayment')
    PropertyVisitPayment.objects.filter(status='completed').update(status='successful')


def standardize_payment_methods_forward(apps, schema_editor):
    """
    Standardize payment methods to: cash, mobile_money, online
    Map old methods to new standard ones:
    - 'card', 'credit_card' -> 'online' (since online payment via AZAM Pay)
    - 'bank_transfer' -> 'online' (since processed online)
    - 'check' -> 'cash' (manual/offline payment)
    - 'other' -> 'online' (default to online)
    - Keep: 'cash', 'mobile_money', 'online' as is
    """
    Payment = apps.get_model('payments', 'Payment')
    
    # Map old payment methods to new standard ones
    method_mapping = {
        'card': 'online',
        'credit_card': 'online',
        'bank_transfer': 'online',
        'check': 'cash',
        'other': 'online',
    }
    
    for old_method, new_method in method_mapping.items():
        Payment.objects.filter(payment_method=old_method).update(payment_method=new_method)
    
    # Also update properties.Payment model if it exists
    try:
        PropertyPayment = apps.get_model('properties', 'Payment')
        for old_method, new_method in method_mapping.items():
            PropertyPayment.objects.filter(payment_method=old_method).update(payment_method=new_method)
    except LookupError:
        # Model doesn't exist, skip
        pass
    
    # Update RentPayment model
    try:
        RentPayment = apps.get_model('rent', 'RentPayment')
        for old_method, new_method in method_mapping.items():
            RentPayment.objects.filter(payment_method=old_method).update(payment_method=new_method)
    except LookupError:
        # Model doesn't exist, skip
        pass


def standardize_payment_methods_reverse(apps, schema_editor):
    """
    Reverse: Map back to original methods (approximate)
    Note: This is lossy - we can't know which original method was used
    """
    Payment = apps.get_model('payments', 'Payment')
    
    # Reverse mapping (approximate - we default to most common)
    reverse_mapping = {
        'online': 'credit_card',  # Default online to credit_card
        'cash': 'cash',  # Keep as is
        'mobile_money': 'mobile_money',  # Keep as is
    }
    
    # This is a best-effort reverse - we can't perfectly restore
    # For now, we'll leave it as is since the forward migration is the important one


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_rent_period'),
    ]

    operations = [
        migrations.RunPython(
            update_visit_payment_status_forward,
            update_visit_payment_status_reverse,
        ),
        migrations.RunPython(
            standardize_payment_methods_forward,
            standardize_payment_methods_reverse,
        ),
    ]
