# Generated by Django 5.2.6 on 2026-01-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_standardize_payment_status_and_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money (AZAM Pay)'), ('online', 'Online Payment (AZAM Pay)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyvisitpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
