# Generated by Django 5.2.6 on 2026-01-12 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_payment_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the booking was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who soft deleted this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag - hides booking from main lists'),
        ),
    ]
