# Generated by Django 5.2.6 on 2025-11-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
