# Generated by Django 5.2.6 on 2025-10-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for staff', null=True),
        ),
    ]
