# Generated by Django 5.2.6 on 2025-10-08 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of the complaint', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the complaint')),
                ('category', models.CharField(choices=[('property', 'Property Issue'), ('service', 'Service Quality'), ('payment', 'Payment Issue'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', help_text='Category of the complaint', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the complaint', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the complaint', max_length=20)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating given by the user (1-5 stars)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Date when the complaint was resolved', null=True)),
                ('property', models.ForeignKey(blank=True, help_text='Property related to the complaint (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Staff member who resolved the complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who submitted the complaint', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('internal', 'Internal Note'), ('user', 'Response to User'), ('update', 'Status Update')], default='user', help_text='Type of response', max_length=20)),
                ('message', models.TextField(help_text='Response content')),
                ('is_visible_to_user', models.BooleanField(default=True, help_text='Whether this response is visible to the complaint submitter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(help_text='The complaint this response is for', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='complaints.complaint')),
                ('responder', models.ForeignKey(help_text='Staff member providing the response', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('general', 'General Feedback'), ('rating', 'App Rating')], default='general', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Feedback content')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating from 1-5 stars', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, help_text='Property this feedback is about (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(help_text='User providing feedback', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
