# Generated by Django 5.2.6 on 2025-11-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status_change_reason',
            field=models.TextField(blank=True, help_text='Reason for changing status from resolved (required when changing from resolved status)', null=True),
        ),
    ]
